#!/bin/sh
while read file
do
    case "$1" in
        "C-k") rm "$file" ;;
        "C-r") convert -rotate 90 "$file" "$file" ;;
        "C-f") convert -flop "$file" "$file" ;;
        "C-c") echo -n "$file" | xsel -ib ;;
        "C-s") if [ $F ]; then
                   cp "$file" $F
                   dunstify -I "$file" "󰁅 Saved 󰁅" "$(basename $file)"
               fi
               ;;
        "C-m") xwallpaper --maximize "$file";;
        "C-t") xwallpaper --tile "$file";;
        "C-w") xwallpaper --stretch "$file";;
    esac
done
